from django.conf.urls import url

from shop.views import (
    HomeView,
    ItemCreateView,
    ItemDetailView,
    ItemPendingListView,
    ShoppingCartListView,
    ContactUsTemplateView,
    confirm_item,
    confirm_u_item,
    add_to_cart,
    delete_from_cart,
    CategoryListView,
    ItemUpdatingListView,
    search,
    ItemUpdateView,
    CheckOut,
    item_delete,
    ItemDeletedListView,
    confirm_deleted_item,
    StaticsListView,
    checkout_final,
    MyOrdersListView,
    comment,
    FeedBacksListView,
    update_quantity,
)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^q/$', search, name='search'),
    url(r'^item/create/$', ItemCreateView.as_view(), name='create'),
    url(r'^item/item_delete/(?P<pk>\d+)/$', item_delete, name='item_delete'),
    url(r'^item/update/(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='update'),
    url(r'^item/add/(?P<id>\d+)/$', add_to_cart, name='add_to_cart'),
    url(r'^item/delete/(?P<id>\d+)/$', delete_from_cart, name='delete_from_cart'),
    url(r'^item/(?P<slug>[-\w]+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^items/pending/$', ItemPendingListView.as_view(), name='pending_items'),
    url(r'^items/updated/$', ItemUpdatingListView.as_view(), name='updated_items'),
    url(r'^items/deleted/$', ItemDeletedListView.as_view(), name='deleted_items'),
    url(r'^item/pending/confirm/$', confirm_item, name='confirm_item'),
    url(r'^item/updated/confirm/$', confirm_u_item, name='confirm_u_item'),
    url(r'^item/deleted/confirm/$', confirm_deleted_item, name='confirm_deleted_item'),
    url(r'^update_quantity/$', update_quantity, name='update_quantity'),
    url(r'^statics/$', StaticsListView.as_view(), name='statics'),
    url(r'^cart/$', ShoppingCartListView.as_view(), name='cart'),
    url(r'^cart/checkout/$', CheckOut.as_view(), name='checkout'),
    url(r'^cart/checkout/final/$', checkout_final, name='checkout_final'),
    url(r'^contact-us/$', ContactUsTemplateView.as_view(), name='contact_us'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryListView.as_view(), name='categories'),
    url(r'^my_orders/$', MyOrdersListView.as_view(), name='my_orders'),
    url(r'^feedbacks/$', FeedBacksListView.as_view(), name='feedbacks'),
    url(r'^comment/done/$', comment, name='comment'),
]
