# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
