# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('shop', '0003_item_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Distributor'),
            preserve_default=False,
        ),
    ]
