# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20171217_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.ShoppingCart'),
            preserve_default=False,
        ),
    ]
