# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
    ]
